[package]
name = "seite"
version = "0.1.3"
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
anyhow = "1.0.83"
clap = { version = "4.5.4", features = ["derive"] }
itertools = "0.13.0"
pulldown-cmark = "0.11.0"
tera = "1.19.1"
