name: CI

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Format
      run: cargo fmt --check --all
    - name: Clippy
      run: cargo clippy
    - name: Rustdoc
      run: cargo doc --no-deps
  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add x86_64-unknown-linux-musl
      - run: cargo build --release --target x86_64-unknown-linux-musl
      - run: tar -cvf x86_64-unknown-linux-musl.tar.gz -C target/x86_64-unknown-linux-musl/release seite
      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: '*.tar.gz'
